//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder",
        "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal Message()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState
            .Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("Core.Message.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState
            .Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registro de Usuario.
        /// </summary>
        public static string LOGIN_00001
        {
            get { return ResourceManager.GetString("LOGIN_00001", resourceCulture); }
        }

        public static string LOGIN_00002
        {
            get { return ResourceManager.GetString("LOGIN_00002", resourceCulture); }
        }

        public static string LOGIN_00003
        {
            get { return ResourceManager.GetString("LOGIN_00003", resourceCulture); }
        }

        public static string LOGIN_00004
        {
            get { return ResourceManager.GetString("LOGIN_00004", resourceCulture); }
        }

        public static string TOKEN_00001
        {
            get { return ResourceManager.GetString("TOKEN_00001", resourceCulture); }
        }

        public static string USER_00001
        {
            get { return ResourceManager.GetString("USER_00001", resourceCulture); }
        }

        public static string USER_00002
        {
            get { return ResourceManager.GetString("USER_00002", resourceCulture); }
        }
        public static string USER_00003 
        {
            get { return ResourceManager.GetString("USER_00003", resourceCulture); }
        }
        public static string USER_00004 
        {
            get { return ResourceManager.GetString("USER_00004", resourceCulture); }
        }
        
        public static string USER_00005 
        {
            get { return ResourceManager.GetString("USER_00005", resourceCulture); }
        }
        
        public static string USER_00006 
        {
            get { return ResourceManager.GetString("USER_00006", resourceCulture); }
        }
        
        public static string USER_00007 
        {
            get { return ResourceManager.GetString("USER_00007", resourceCulture); }
        }
        
        public static string USER_00008 
        {
            get { return ResourceManager.GetString("USER_00008", resourceCulture); }
        }
        
        public static string USER_00009 
        {
            get { return ResourceManager.GetString("USER_00009", resourceCulture); }
        }
        
        public static string USER_00010 
        {
            get { return ResourceManager.GetString("USER_00010", resourceCulture); }
        }
        
        public static string LOGOUT_00001
        {
            get { return ResourceManager.GetString("LOGOUT_00001", resourceCulture); }
        }

        public static string MPASS_0001
        {
            get { return ResourceManager.GetString("MPASS_0001", resourceCulture); }
        }

        public static string MPASS_0002
        {
            get { return ResourceManager.GetString("MPASS_0002", resourceCulture); }
        }

        public static string MPASS_0003
        {
            get { return ResourceManager.GetString("MPASS_0003", resourceCulture); }
        }

        public static string MPASS_0004
        {
            get { return ResourceManager.GetString("MPASS_0004", resourceCulture); }
        }

        public static string MPASS_0005
        {
            get { return ResourceManager.GetString("MPASS_0005", resourceCulture); }
        }

        public static string MCLAVE_0001 
        {
            get { return ResourceManager.GetString("MCLAVE_0001", resourceCulture); } 
        }
        public static string MCLAVE_0002 
        {
            get { return ResourceManager.GetString("MCLAVE_0002", resourceCulture); } 
        }
        public static string MCLAVE_0003 
        {
            get { return ResourceManager.GetString("MCLAVE_0003", resourceCulture); } 
        }
        public static string MCLAVE_0004 
        {
            get { return ResourceManager.GetString("MCLAVE_0004", resourceCulture); } 
        }
        public static string MCLAVE_0005 
        {
            get { return ResourceManager.GetString("MCLAVE_0005", resourceCulture); } 
        }

        public static string CAT_0001
        {
            get { return ResourceManager.GetString("CAT_0001", resourceCulture); }
        }
        
        public static string CAT_0002
        {
            get { return ResourceManager.GetString("CAT_0002", resourceCulture); }
        }
        
        public static string CAT_0003
        {
            get { return ResourceManager.GetString("CAT_0003", resourceCulture); }
        }
        
        public static string CAT_0004
        {
            get { return ResourceManager.GetString("CAT_0004", resourceCulture); }
        }
        
        public static string CAT_0005
        {
            get { return ResourceManager.GetString("CAT_0005", resourceCulture); }
        }
        
        public static string CAT_0006
        {
            get { return ResourceManager.GetString("CAT_0006", resourceCulture); }
        }
        
        public static string CAT_0007
        {
            get { return ResourceManager.GetString("CAT_0007", resourceCulture); }
        }
        
        public static string CAT_0008
        {
            get { return ResourceManager.GetString("CAT_0008", resourceCulture); }
        }
        
        public static string CAT_0009
        {
            get { return ResourceManager.GetString("CAT_0009", resourceCulture); }
        }
        
        public static string FIS_0001
        {
            get { return ResourceManager.GetString("FIS_0001", resourceCulture); }
        }
        
        public static string FIS_0002
        {
            get { return ResourceManager.GetString("FIS_0002", resourceCulture); }
        }
        
        public static string FIS_0003
        {
            get { return ResourceManager.GetString("FIS_0003", resourceCulture); }
        }
        
        public static string FIS_0004
        {
            get { return ResourceManager.GetString("FIS_0004", resourceCulture); }
        }
        
        public static string FIS_0005
        {
            get { return ResourceManager.GetString("FIS_0005", resourceCulture); }
        }
        
        public static string FIS_0006
        {
            get { return ResourceManager.GetString("FIS_0006", resourceCulture); }
        }
        
        public static string FIS_0007
        {
            get { return ResourceManager.GetString("FIS_0007", resourceCulture); }
        }

        public static string FIS_0008 { get { return ResourceManager.GetString("FIS_0008", resourceCulture); } }
        public static string FIS_0009 { get { return ResourceManager.GetString("FIS_0009", resourceCulture); } }

        public static string PACI_0001 
        {
            get { return ResourceManager.GetString("PACI_0001", resourceCulture); }
        }
        public static string PACI_0002 
        {
            get { return ResourceManager.GetString("PACI_0002", resourceCulture); }
        }
        public static string PACI_0003 
        {
            get { return ResourceManager.GetString("PACI_0003", resourceCulture); }
        }
        public static string PACI_0004 
        {
            get { return ResourceManager.GetString("PACI_0004", resourceCulture); }
        }
        public static string PACI_0005 
        {
            get { return ResourceManager.GetString("PACI_0005", resourceCulture); }
        }
        public static string PACI_0006 
        {
            get { return ResourceManager.GetString("PACI_0006", resourceCulture); }
        }
        public static string PACI_0007 
        {
            get { return ResourceManager.GetString("PACI_0007", resourceCulture); }
        }
        public static string PACI_0008 
        {
            get { return ResourceManager.GetString("PACI_0008", resourceCulture); }
        }
        public static string PACI_0009 
        {
            get { return ResourceManager.GetString("PACI_0009", resourceCulture); }
        }
        public static string PACI_0010 
        {
            get { return ResourceManager.GetString("PACI_0010", resourceCulture); }
        }
        public static string PACI_0011 
        {
            get { return ResourceManager.GetString("PACI_0011", resourceCulture); }
        }
        public static string PACI_0012 
        {
            get { return ResourceManager.GetString("PACI_0012", resourceCulture); }
        }
        public static string PACI_0013 
        {
            get { return ResourceManager.GetString("PACI_0013", resourceCulture); }
        }
        public static string PACI_0014 
        {
            get { return ResourceManager.GetString("PACI_0014", resourceCulture); }
        }
        public static string PACI_0015 { get { return ResourceManager.GetString("PACI_0015", resourceCulture); } }
        public static string PACI_0016 { get { return ResourceManager.GetString("PACI_0016", resourceCulture); } }
        public static string PACI_0017 { get { return ResourceManager.GetString("PACI_0017", resourceCulture); } }

        public static string EXP_0001
        {
            get { return ResourceManager.GetString("EXP_0001", resourceCulture); }
        }
        
        public static string EXP_0002
        {
            get { return ResourceManager.GetString("EXP_0002", resourceCulture); }
        }
        
        public static string EXP_0003
        {
            get { return ResourceManager.GetString("EXP_0003", resourceCulture); }
        }
        
        public static string EXP_0004
        {
            get { return ResourceManager.GetString("EXP_0004", resourceCulture); }
        }
        
        public static string EXP_0005
        {
            get { return ResourceManager.GetString("EXP_0005", resourceCulture); }
        }
        
        public static string EXP_0006
        {
            get { return ResourceManager.GetString("EXP_0006", resourceCulture); }
        }

        public static string EXP_0007
        {
            get { return ResourceManager.GetString("EXP_0007", resourceCulture); }
        }

        public static string EXP_0008
        {
            get { return ResourceManager.GetString("EXP_0008", resourceCulture); }
        }

        public static string EXP_0009
        {
            get { return ResourceManager.GetString("EXP_0009", resourceCulture); }
        }

        public static string EXP_0010
        {
            get { return ResourceManager.GetString("EXP_0010", resourceCulture); }
        }

        public static string MAP_0001
        {
            get { return ResourceManager.GetString("MAP_0001", resourceCulture); }
        }
        
        public static string MAP_0002
        {
            get { return ResourceManager.GetString("MAP_0002", resourceCulture); }
        }
        
        public static string MAP_0003
        {
            get { return ResourceManager.GetString("MAP_0003", resourceCulture); }
        }
        
        public static string MAP_0004
        {
            get { return ResourceManager.GetString("MAP_0004", resourceCulture); }
        }

        public static string DIAG_0001 
        {
            get { return ResourceManager.GetString("DIAG_0001", resourceCulture); }
        }
        
        public static string DIAG_0002 
        {
            get { return ResourceManager.GetString("DIAG_0002", resourceCulture); }
        }
        
        public static string DIAG_0003 
        {
            get { return ResourceManager.GetString("DIAG_0003", resourceCulture); }
        }
        
        public static string DIAG_0004 
        {
            get { return ResourceManager.GetString("DIAG_0004", resourceCulture); }
        }
        
        public static string DIAG_0005 
        {
            get { return ResourceManager.GetString("DIAG_0005", resourceCulture); }
        }
        
        public static string DIAG_0006 
        {
            get { return ResourceManager.GetString("DIAG_0006", resourceCulture); }
        }
        
        public static string DIAG_0007 
        {
            get { return ResourceManager.GetString("DIAG_0007", resourceCulture); }
        }
        
        public static string DIAG_0008 
        {
            get { return ResourceManager.GetString("DIAG_0008", resourceCulture); }
        }
        
        public static string DIAG_0009 
        {
            get { return ResourceManager.GetString("DIAG_0009", resourceCulture); }
        }
        
        public static string DIAG_0010 
        {
            get { return ResourceManager.GetString("DIAG_0010", resourceCulture); }
        }
        
        public static string DIAG_0011 
        {
            get { return ResourceManager.GetString("DIAG_0011", resourceCulture); }
        }
        
        public static string DIAG_0012 
        {
            get { return ResourceManager.GetString("DIAG_0012", resourceCulture); }
        }
        
        public static string DIAG_0013 { get { return ResourceManager.GetString("DIAG_0013", resourceCulture); } }
        public static string DIAG_0014 { get { return ResourceManager.GetString("DIAG_0014", resourceCulture); } }
        public static string DIAG_0015 { get { return ResourceManager.GetString("DIAG_0015", resourceCulture); } }
        public static string DIAG_0016 { get { return ResourceManager.GetString("DIAG_0016", resourceCulture); } }
        public static string DIAG_0017 { get { return ResourceManager.GetString("DIAG_0017", resourceCulture); } }
        public static string DIAG_0018 { get { return ResourceManager.GetString("DIAG_0018", resourceCulture); } }
        public static string DIAG_0019 { get { return ResourceManager.GetString("DIAG_0019", resourceCulture); } }
        
        public static string PROG_0001 { get { return ResourceManager.GetString("PROG_0001", resourceCulture); } }
        public static string PROG_0002 { get { return ResourceManager.GetString("PROG_0002", resourceCulture); } }
        public static string PROG_0003 { get { return ResourceManager.GetString("PROG_0003", resourceCulture); } }
        public static string PROG_0004 { get { return ResourceManager.GetString("PROG_0004", resourceCulture); } }
        public static string PROG_0005 { get { return ResourceManager.GetString("PROG_0005", resourceCulture); } }
        public static string PROG_0006 { get { return ResourceManager.GetString("PROG_0006", resourceCulture); } }
        public static string PROG_0007 { get { return ResourceManager.GetString("PROG_0007", resourceCulture); } }
        
        public static string REV_0001 { get { return ResourceManager.GetString("REV_0001", resourceCulture); } }
        public static string REV_0002 { get { return ResourceManager.GetString("REV_0002", resourceCulture); } }
        public static string REV_0003 { get { return ResourceManager.GetString("REV_0003", resourceCulture); } }
        public static string REV_0004 { get { return ResourceManager.GetString("REV_0004", resourceCulture); } }
        
        public static string EXPE_0001 { get { return ResourceManager.GetString("EXPE_0001", resourceCulture); } }
        public static string EXPE_0002 { get { return ResourceManager.GetString("EXPE_0002", resourceCulture); } }
        
        public static string CITA_0001 { get { return ResourceManager.GetString("CITA_0001", resourceCulture); } }
        public static string CITA_0002 { get { return ResourceManager.GetString("CITA_0002", resourceCulture); } }
        public static string CITA_0003 { get { return ResourceManager.GetString("CITA_0003", resourceCulture); } }
        public static string CITA_0004 { get { return ResourceManager.GetString("CITA_0004", resourceCulture); } }
        public static string CITA_0005 { get { return ResourceManager.GetString("CITA_0005", resourceCulture); } }
        
        public static string HERE_0001 { get { return ResourceManager.GetString("HERE_0001", resourceCulture); } }
        public static string HERE_0002 { get { return ResourceManager.GetString("HERE_0002", resourceCulture); } }
        public static string HERE_0003 { get { return ResourceManager.GetString("HERE_0003", resourceCulture); } }
        public static string HERE_0004 { get { return ResourceManager.GetString("HERE_0004", resourceCulture); } }
        public static string HERE_0005 { get { return ResourceManager.GetString("HERE_0005", resourceCulture); } }
        public static string HERE_0006 { get { return ResourceManager.GetString("HERE_0006", resourceCulture); } }
        
        public static string ANTE_0001 { get { return ResourceManager.GetString("ANTE_0001", resourceCulture); } }
        public static string ANTE_0002 { get { return ResourceManager.GetString("ANTE_0002", resourceCulture); } }
        public static string ANTE_0003 { get { return ResourceManager.GetString("ANTE_0003", resourceCulture); } }
        public static string ANTE_0004 { get { return ResourceManager.GetString("ANTE_0004", resourceCulture); } }
        
        public static string GINE_0001 { get { return ResourceManager.GetString("GINE_0001", resourceCulture); } }
        public static string GINE_0002 { get { return ResourceManager.GetString("GINE_0002", resourceCulture); } }
        
        public static string GRAL_0001 { get { return ResourceManager.GetString("GRAL_0001", resourceCulture); } }
        public static string GRAL_0002 { get { return ResourceManager.GetString("GRAL_0002", resourceCulture); } }
        public static string GRAL_0003 { get { return ResourceManager.GetString("GRAL_0003", resourceCulture); } }
        public static string GRAL_0004 { get { return ResourceManager.GetString("GRAL_0004", resourceCulture); } }
        public static string GRAL_0005 { get { return ResourceManager.GetString("GRAL_0005", resourceCulture); } }
        public static string GRAL_0006 { get { return ResourceManager.GetString("GRAL_0006", resourceCulture); } }
    }
}
