namespace Core.Domain.Helpers;

public static class PuntosMapa
{
    public static Dictionary<int, string> MapaHombre()
    {
        Dictionary<int, string> diccionario = new Dictionary<int, string>
        {
            { 1, "Cabeza" },
            { 2, "RCervicalA" },
            { 3, "DeltoidesAI" },
            { 4, "DeltoidesAD" },
            { 5, "BicepI" },
            { 6, "BicepD" },
            { 7, "AntebrazoAI" },
            { 8, "AntebrazoAD" },
            { 9, "MuñecaI" },
            { 10, "MuñecaD" },
            { 11, "ManoI" },
            { 12, "ManoD" },
            { 13, "PechoI" },
            { 14, "PechoD" },
            { 15, "RAbdominal" },
            { 16, "Pelvis" },
            { 17, "MusloAI" },
            { 18, "MusloAD" },
            { 19, "RodillaAI" },
            { 20, "RodillaAD" },
            { 21, "TibialD" },
            { 22, "TibialI" },
            { 23, "TobilloD" },
            { 24, "TobilloI" },
            { 25, "EmpeineI" },
            { 26, "EmpeineD" },
            { 27, "Occipital" },
            { 28, "CervicalP" },
            { 29, "RToracica" },
            { 30, "RLumbar" },
            { 31, "REscapularIzquierda" },
            { 32, "REscapularD" },
            { 33, "TricepsI" },
            { 34, "TricepsD" },
            { 35, "AntebrazoPI" },
            { 36, "AntebrazoPD" },
            { 37, "GluteoI" },
            { 38, "GluteoD" },
            { 39, "IsquiotibialesI" },
            { 40, "IsquiotibialesD" },
            { 41, "RPopliteaI" },
            { 42, "RPopliteaD" },
            { 43, "PantorrillaI" },
            { 44, "PantorrillaD" },
            { 45, "TendonAquilesI" },
            { 46, "TendonAquilesD" },
            { 47, "TalonI" },
            { 48, "TalonD" },
            { 49, "RTemporal" },
            { 50, "RMandibular" },
            { 51, "RCervicalL" },
            { 52, "RtoracicaL" },
            { 53, "DeltoidesL" },
            { 54, "Codo" },
            { 55, "RIliaca" },
            { 56, "MusloL" }
        };
        
        return diccionario;
    }

    public static Dictionary<int, string> MapaMujer()
    {
        Dictionary<int, string> diccionario = new Dictionary<int, string>
        {
            { 1, "CabezaA" },
            { 2, "RCervicalA" },
            { 3, "DeltoidesAI" },
            { 4, "DeltoidesAD" },
            { 5, "BicepI" },
            { 6, "BicepD" },
            { 7, "AntebrazoAI" },
            { 8, "AntebrazoAD" },
            { 9, "MuñecaI" },
            { 10, "MuñecaD" },
            { 11, "ManoI" },
            { 12, "ManoD" },
            { 13, "PechoI" },
            { 14, "PechoD" },
            { 15, "RAbdominalA" },
            { 16, "RPelvisA" },
            { 17, "MusloAI" },
            { 18, "MusloAD" },
            { 19, "RodillaAI" },
            { 20, "RodillaAD" },
            { 22, "TibialI" },
            { 21, "TibialD" },
            { 23, "TobilloD" },
            { 24, "TobilloI" },
            { 25, "EmpeineI" },
            { 26, "EmpeineD" },
            { 27, "ROccipitalP" },
            { 28, "RCervicalP" },
            { 29, "RToracicaP" },
            { 30, "RLumbarP" },
            { 31, "REscapularI" },
            { 32, "REscapularD" },
            { 33, "TricepsI" },
            { 34, "TricepsD" },
            { 35, "AntebrazoPI" },
            { 36, "AntebrazoPD" },
            { 37, "GluteoI" },
            { 38, "GluteoD" },
            { 39, "IsquiotibialesI" },
            { 40, "IsquiotibialesD" },
            { 41, "RPopliteaI" },
            { 42, "RPopliteaD" },
            { 43, "PantorrillaI" },
            { 44, "PantorrillaD" },
            { 45, "TendonAquilesI" },
            { 46, "TendonAquilesD" },
            { 47, "TalonI" },
            { 48, "TalonD" },
            { 49, "RTemporal" },
            { 50, "RMandibular" },
            { 51, "RCervicalL" },
            { 52, "RToracicaL" },
            { 53, "DeltoidesL" },
            { 54, "CodoL" },
            { 55, "RIliaca" },
            { 56, "MusloLateral" }
        };
        
        return diccionario;
    }
}